# Generated by Django 4.0.6 on 2022-10-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction_account_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.IntegerField(null=True),
        ),
    ]
