# Generated by Django 4.0.6 on 2022-07-30 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_customer_employment_status_customer_marital_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True)),
                ('pin', models.SmallIntegerField(blank=True, max_length=8)),
                ('active', models.BooleanField()),
                ('datecreated', models.DateTimeField()),
                ('type', models.CharField(max_length=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
    ]
