# Generated by Django 4.0.6 on 2022-07-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='Wallets',
        ),
    ]
